<?php

namespace Tests\Feature;

use App\Models\Barcode;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class StorageLabelsTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->user = User::factory()->create();
    }

    public function test_bag_labels_are_registered_with_sequential_codes(): void
    {
        $response = $this->actingAs($this->user)->post('/storage/labels', ['type' => 'bag', 'count' => 3]);

        $this->assertSame(['BAG-000001', 'BAG-000002', 'BAG-000003'], Barcode::orderBy('id')->pluck('code')->all());

        // A second run continues the sequence — codes are never reissued.
        $this->actingAs($this->user)->post('/storage/labels', ['type' => 'bag', 'count' => 2]);
        $this->assertSame('BAG-000005', Barcode::orderBy('id')->get()->last()->code);

        $run = Barcode::first()->print_run;
        $response->assertRedirect(route('labels.print', ['run' => $run]));
    }

    public function test_divider_labels_are_counted_with_optional_names(): void
    {
        // A divider is a location marker: generated by quantity like bags
        // and boxes. Names are optional decoration for the first labels.
        $this->actingAs($this->user)->post('/storage/labels', [
            'type' => 'divider',
            'count' => 3,
            'names' => "Baseball 80s\n\nFootball Stars\n",
        ]);

        $barcodes = Barcode::orderBy('id')->get();
        $this->assertCount(3, $barcodes);
        $this->assertSame('DIV-000001', $barcodes[0]->code);
        $this->assertSame('Baseball 80s', $barcodes[0]->label);
        $this->assertSame('Football Stars', $barcodes[1]->label);
        $this->assertNull($barcodes[2]->label);
    }

    public function test_divider_labels_need_no_names_at_all(): void
    {
        $this->actingAs($this->user)->post('/storage/labels', ['type' => 'divider', 'count' => 2]);

        $barcodes = Barcode::orderBy('id')->get();
        $this->assertCount(2, $barcodes);
        $this->assertNull($barcodes[0]->label);
        $this->assertNull($barcodes[1]->label);
    }

    public function test_more_names_than_labels_is_rejected(): void
    {
        $this->actingAs($this->user)
            ->post('/storage/labels', ['type' => 'divider', 'count' => 1, 'names' => "One\nTwo"])
            ->assertSessionHasErrors('names');

        $this->assertSame(0, Barcode::count());
    }

    public function test_print_sheet_renders_a_barcode_per_label(): void
    {
        $this->actingAs($this->user)->post('/storage/labels', ['type' => 'box', 'count' => 2]);
        $run = Barcode::first()->print_run;

        $this->actingAs($this->user)
            ->get("/storage/labels/{$run}")
            ->assertOk()
            ->assertInertia(fn (AssertableInertia $page) => $page
                ->component('LabelPrint')
                ->has('labels', 2)
                ->where('labels.0.code', 'BOX-000001')
                ->where('labels.0.svg', fn ($svg) => str_contains((string) $svg, '<svg'))
            );
    }

    public function test_unknown_print_run_is_not_found(): void
    {
        $this->actingAs($this->user)->get('/storage/labels/not-a-run')->assertNotFound();
    }

    public function test_labels_require_authentication(): void
    {
        $this->get('/storage/labels')->assertRedirect('/login');
        $this->post('/storage/labels', ['type' => 'bag', 'count' => 1])->assertRedirect('/login');
    }
}
